### ISSUE TITLE
backupSD.sh/restore.sh : Add warning about device_data and SDLicense if Deviceidentifier differs.

### ISSUE THREAD

**Issue by martinboers** [PLCnext/UtilityScripts#6]
"Device data" includes data that is specific to an individual device, e.g. data that is tied to the specific trusted platform module (TPM) chip in the device. As a result, device data should NEVER be restored to a device other than the device from which it was copied. Attempting to restore device data to a different device will make that device inoperable and unrecoverable.

**Comment by martinboers** [comment]
Sorry, I should have read the script.  :)

**Comment by OWarneke** [comment]
I should also add a SerialNumber comparison etc.
If the data are not corrupted yet we can make sure that it will not overwrite an otherwise perfectly fine device.

**Comment by OWarneke** [comment]
- [x ] [SD Licence Validation during restore](https://github.com/PLCnext/UtilityScripts/commit/fcc99df7f365cda200cb2ea1a10afdcdfc565d6a)
- [x ] [device data validation during restore](https://github.com/PLCnext/UtilityScripts/commit/066cc6cb78a328a0862a5a1f9580995e42699cce)
